import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Services from "@/components/Services";
import AboutUs from "@/components/About";
import gsap from "gsap";
import ContactUs from "@/components/ContactUs";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <Services />
        <AboutUs />
        <ContactUs />

      </body>
    </html>
  );
}
